name = "bookmark-api"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "bookmarks"
database_id = "" # 部署时在Cloudflare控制台获取并填写

[vars]
# 这些变量将在Cloudflare Workers控制台中设置
# ADMIN_PASSWORD - 管理员密码
# JWT_SECRET - 用于JWT令牌的密钥（可选）
